### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by tsh-y-suzuki**
テストプルリクエスト
コンパイル時エラーは常に有効になり、実行時エラーはconfigのzero_division_error: yesで有効になる。

### CODE REVIEW

**Comment by GitMensch** [comment]
Just a hint for other readers: the translation is:

>Compile-time errors are always enabled, and run-time errors are enabled in config's `zero_division_error: yes`.
> Added check processing to issue compile-time error and run-time error at division by zero.

@tsh-y-suzuki : Can you please add an entry in tests/syntax.scr/ and tests/run.src/ ? This has three use cases: it shows even better what the code changes are supposed to do, it verifies it does this after your changes and it ensures that future changes do not break your changes.

**Comment by tsh-y-suzuki** [comment]
@GitMensch Thanks for the comment, I'll work on it.

**Comment by GitMensch** [comment]
@tsh-y-suzuki Is there an update you can share about the current progress?

**Comment by tsh-y-suzuki** [comment]
Sorry, No Update right now, I'll work on writng test code.

**Comment by n-isaka** [comment]
I created a modified version and a test case at #38 .
I want to close this PR.

**Comment by tsh-y-suzuki** [comment]
I closed. Thank you n-isaka.

**Pull request closed without merging**
